FROM lunamidori5/pixelarch:latest

RUN sudo sed -i 's/Quartz/Cluster/g' /etc/os-release

RUN yay -Syu --noconfirm tar && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm curl && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm wget && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm unzip && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm zip && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm jq && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm tree && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm lolcat && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm fish && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm tmate && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm fastfetch && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm bash-completion && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm cmake && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm python && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm python311 && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm python310 && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm uv && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm docker && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm docker-compose && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm nvidia-container-toolkit && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm python-pyfiglet && yay -Yccc --noconfirm
RUN yay -Syu --noconfirm python-virtualenv && yay -Yccc --noconfirm

RUN echo "sudo rm -rf /var/lib/pacman/db.lck" > executable.sh
RUN echo "yay -Syu --noconfirm" >> executable.sh

RUN echo "uv venv --link-mode=copy os" >> executable.sh
RUN echo "uv pip install -U --no-cache-dir cryptography aiohttp psutil pytz climage diskcache requests subprocess32 tqdm" >> executable.sh

RUN echo "midori-ai-downloader aicluster_prod.py" >> executable.sh
RUN echo "mv aicluster_prod.py aicluster.py" >> executable.sh

RUN echo "uv run aicluster.py" >> executable.sh

RUN chmod +x executable.sh

ENTRYPOINT [ "bash", "executable.sh" ]
