FROM lunamidori5/pixelarch:latest

RUN yay -Syu --noconfirm python tar curl wget tmate-git fastfetch-git bash-completion-git
RUN yay -Syu --noconfirm unzip zip tree nvidia-container-toolkit jq lolcat
RUN yay -Syu --noconfirm python-pyfiglet python-virtualenv
RUN yay -Syu --noconfirm python311 python310 docker docker-compose

RUN yay -Ycc --noconfirm

# Make the python venv
# use "os/bin/python" for python
# use "os/bin/pip" for pip

RUN echo "yay -Syu --noconfirm" > executable.sh

RUN echo "rm -rf os" >> executable.sh

RUN echo "python3 -m venv os" >> executable.sh

RUN echo "os/bin/pip install -U --no-cache-dir cryptography aiohttp psutil pytz climage" >> executable.sh
RUN echo "os/bin/pip install -U --no-cache-dir diskcache requests subprocess32 tqdm" >> executable.sh
RUN echo "os/bin/pip install -U --no-cache-dir git+https://github.com/pyinstaller/pyinstaller" >> executable.sh

RUN echo "test -f helper_app.py || wget https://tea-cup.midori-ai.xyz/download/helper_app.py" >> executable.sh

RUN echo "os/bin/python helper_app.py aicluster_prod.py" >> executable.sh
RUN echo "mv aicluster_prod.py aicluster.py" >> executable.sh

RUN echo "os/bin/python aicluster.py" >> executable.sh

RUN chmod +x executable.sh

ENTRYPOINT [ "bash", "executable.sh" ]



